sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wy965478
  redis:
    host: localhost
    port: 6379
    password: wy965478
    database: 1
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7hTFaZKwvGeUCZbTNV
    access-key-secret: UDPNDM8vxH06TLuD5AIZtKIKFcF3iM
    bucket-name: sky-web
  wechat:
    appid: wxa65f2158535a818d
    secret: 8e8b00a127cecae48b6241a05a9785b1
